// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SOLUDIAMAGHREB.Data;

#nullable disable

namespace SOLUDIAMAGHREB.Migrations
{
    [DbContext(typeof(DbsoludiaContext))]
    [Migration("20241025160220_IntDB_AddTableActManager")]
    partial class IntDB_AddTableActManager
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SOLUDIAMAGHREB.Models.Actmanager", b =>
                {
                    b.Property<string>("IdactEng")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Appel_Offres")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Capital")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CAST(GETDATE() AS DATE)");

                    b.Property<string>("Marche_passe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MontantDh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Montant_DH");

                    b.Property<int>("MontantHtTva")
                        .HasColumnType("int")
                        .HasColumnName("Montant_HT_TVA");

                    b.Property<int>("MontantTva")
                        .HasColumnType("int")
                        .HasColumnName("Montant_TVA");

                    b.Property<int>("MontantTvaComprise")
                        .HasColumnType("int")
                        .HasColumnName("Montant_TVA_Comprise");

                    b.Property<string>("NLot")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Objet_du_Marche")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TauxTva")
                        .HasColumnType("int")
                        .HasColumnName("Taux_TVA");

                    b.HasKey("IdactEng")
                        .HasName("PK__ActManager");

                    b.ToTable("ACTMANAGER", (string)null);
                });

            modelBuilder.Entity("SOLUDIAMAGHREB.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Clave")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("Email")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("Nom")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("Prenom")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("UserName")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)");

                    b.HasKey("IdUser")
                        .HasName("PK__Utilisat__3717C98297588A3A");

                    b.ToTable("Utilisateur", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
